### ISSUE TITLE
LDAP Login Issue

### ISSUE THREAD

**Issue by kthibodeaux** [sdelements/lets-chat-ldap#20]
An improper username or password will give an error, but a proper user and password throws this exception:

```
Release 0.4.2


/opt/bitnami/node_modules/mongoose/lib/index.js:333
      throw new mongoose.Error.MissingSchemaError(name);
      ^
MissingSchemaError: Schema hasn't been registered for model "User".
Use mongoose.model(name, schema)
    at Mongoose.model (/opt/bitnami/node_modules/mongoose/lib/index.js:333:13)
    at Function.Ldap.findOrCreateFromLDAP (/opt/bitnami/node_modules/lets-chat-ldap/lib/auth.js:75:25)
    at Ldap.<anonymous> (/opt/bitnami/node_modules/lets-chat-ldap/lib/auth.js:69:25)
    at null.<anonymous> (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js:187:21)
    at /opt/bitnami/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/node_modules/ldapauth-fork/lib/ldapauth.js:333:18
    at LdapAuth._getGroups (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/node_modules/ldapauth-fork/lib/ldapauth.js:143:14)
    at /opt/bitnami/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/node_modules/ldapauth-fork/lib/ldapauth.js:322:12
    at _done (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/ldapjs/lib/client/client.js:791:12)
    at messageCallback (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/ldapjs/lib/client/client.js:869:16)
    at Parser.onMessage (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/ldapjs/lib/client/client.js:199:12)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Parser.write (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/ldapjs/lib/messages/parser.js:105:8)
    at Socket.onData (/opt/bitnami/node_modules/lets-chat-ldap/node_modules/ldapjs/lib/client/client.js:155:24)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

I am able to use the local auth provider and create accounts.  Is there an easy fix for this?  Thanks!

**Comment by Cyberwizzard** [comment]
I'm using Let's Chat 0.4.8 and see the same error - is this plugin this working?
